``` mermaid
erDiagram
    movie_lookup {
    text input_name PK
    text matched_name
    bigint tvdb_id "UNIQUE (partial, non-null)"
    }

    movies {
    bigint id PK
    text name
    text slug
    int runtime
    int year
    text genres
    bigint budget
    bigint box_office
    text original_country
    text original_language
    text franchise
    text record_type
    boolean acquired
    }

    movies_cast {
    bigint id PK
    bigint people_id
    bigint movie_id
    text person_name
    text role_name
    text people_type
    }

    series {
    bigint id PK
    text name
    text slug
    text genres
    int year
    text franchise
    text original_country
    text original_language
    boolean acquired
    }

    series_cast {
    bigint id PK
    bigint people_id
    bigint series_id FK
    text person_name
    text role_name
    text people_type
    }

    series_eps {
    bigint id PK
    bigint seriesid FK
    text name
    date aired
    text overview
    int number
    int absolutenumber
    int seasonnumber
    int year
    }

    series_lookup {
    text input_name PK
    text matched_name
    bigint tvdb_id "UNIQUE (partial, non-null)"
    }

    series ||--o{ series_cast : has
    series ||--o{ series_eps : contains

```